input('What do you get when you cross a snowman with a vampire?')
print('Frostbite!')
print()
input('What do dentists call a astronaut\'s cavity?')
print('A black hole!')
print()
input('Knock knock.')
input("Who's there?")
input('Interrupting cow.')
print('Interrupting cow wh', end='')
print('-MOO!')
print()
input('What\'s black and white and read all over?')
print('A Newspaper!')
print()
input('Why did the chicken cross the road?')
input(("to get to the other side").upper())
print()
input(('IT\'S NOT UKRANIAN BAKERY \nITS MY KRANIAN BAKERY').lower())
print()

x=input('What is your name \"young jokester\"?')
print('Nice to meet you ' + x)
input('Press enter to end '+x+'.')
